# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lemonldap-NG-Handler
version:      0.1
version_from: lib/Lemonldap/NG/Handler.pm
installdirs:  site
requires:
    Apache:                        0
    Apache::Constants:             0
    Apache::Session:               0
    Cache::Cache:                  0
    DBI:                           0
    LWP::UserAgent:                0
    MIME::Base64:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
