--- #YAML:1.0
name:               Lemonldap-NG-Handler
version:            1.2.5
abstract:           The Apache protection module part of
author:
    - Xavier Guimard <x.guimard@free.fr>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Cache::Memcached:   0
    Digest::HMAC_SHA1:  0
    HTTP::Message:      0
    IO::Pipe:           0
    SOAP::Lite:         0
    Test::MockObject:   0
    Test::Pod:          0
requires:
    Apache::Session::Generate::MD5:  0
    CGI:                  3.08
    Lemonldap::NG::Common:  1.2.4
    LWP:                  0
    URI:                  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    Cache::Memcached:     0
    Digest::HMAC_SHA1:    0
    HTTP::Message:        0
    LWP::Protocol::https:  0
    SOAP::Lite:           0
