--- #YAML:1.0
name:                Lemonldap-NG-Handler
version:             0.91
abstract:            The Apache protection module part of
license:             ~
author:              
    - Xavier Guimard <x.guimard@free.fr>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Apache::Session:               0
    Cache::Cache:                  0
    CGI:                           3.08
    IO::Pipe:                      0
    Lemonldap::NG::Common:         0.93
    LWP::UserAgent:                0
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
