--- #YAML:1.0
name:                Lemonldap-NG-Handler
version:             0.89
abstract:            The Apache protection module part of
license:             ~
author:              
    - Xavier Guimard <x.guimard@free.fr>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Apache::Session:               0
    Cache::Cache:                  0
    IO::Pipe:                      0
    Lemonldap::NG::Manager:        0.4
    LWP::UserAgent:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
